spring:
  application:
    name: product-ui
  config:
    import: "optional:configserver:"
  cloud:
    config:
      # label specifies the repo branch from client side to target at server: http://localhost:8888/product-ui/dev/develop
      # where product-ui = {application-name}, dev = {profile}, develop = {git-repo-branch}
      label: develop
      enabled: false