server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alrealor/skt-microservices-task
#          uri: ${HOME}/Documents/dev/workspaces/skytouch/skt-microservices-task/config-repo
          # default-label specifies the git repo branch from server side
          default-label: develop
          repos:
            dev-env:
              pattern: product-ui/dev, product-service/dev
#              uri: ${HOME}/Documents/dev/workspaces/skytouch/skt-microservices-task/config-repo
              uri: https://github.com/alrealor/skt-microservices-task
              search-paths:
                - env-config/dev

