server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alrealor/skt-microservices-task
#          uri: ${HOME}/Documents/dev/workspaces/skytouch/skt-microservices-task/config-repo
          default-label: develop
          repos:
            development:
              pattern: product-ui/dev, product-service/dev
#              uri: ${HOME}/Documents/dev/workspaces/skytouch/skt-microservices-task/config-repo
              uri: https://github.com/alrealor/skt-microservices-task
              search-paths:
                - dev
#            any-request-repo:
#              uri: ${HOME}/Documents/dev/workspaces/skytouch/skt-microservices-task/configrepo
#              pattern: product-ui*/*
#              search-paths:
#                - /{application}-{profile}

