openapi: "3.0.3"
info:
  title: "skytouch_task API"
  description: "skytouch_task API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8081"
paths:
  /products:
    get:
      summary: "GET products"
      operationId: "getProducts"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
    post:
      summary: "POST products"
      operationId: "addProduct"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostProductRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
components:
  schemas:
    Object:
      type: "object"
      properties: { }
    HttpHeaders:
      type: "object"
      properties: { }
    ResponseEntity:
      type: "object"
      properties:
        statusCode:
          $ref: "#/components/schemas/Object"
        headers:
          $ref: "#/components/schemas/HttpHeaders"
    BigDecimal:
      type: "object"
      properties: { }
    PostProductRequest:
      type: "object"
      properties:
        name:
          type: "string"
        price:
          $ref: "#/components/schemas/BigDecimal"